"""Initial quotation schema

Revision ID: 29c9874f4150
Revises:
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "29c9874f4150"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("window_started", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "master_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item", sa.String(length=200), nullable=False),
        sa.Column("carcass", sa.String(length=200), nullable=False),
        sa.Column("shutter", sa.String(length=200), nullable=False),
        sa.Column("finish", sa.String(length=250), nullable=False),
        sa.Column("combination_key", sa.String(length=900), nullable=False),
        sa.Column("price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("other", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("hardware", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("pricing_area", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("source_data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("combination_key"),
    )
    with op.batch_alter_table("master_products", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_master_products_item"), ["item"], unique=False
        )

    op.create_table(
        "quotation_counters",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("year"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity", sa.String(length=100), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=60), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("project_reference", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "price_conflicts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("item", sa.String(length=200), nullable=False),
        sa.Column("carcass", sa.String(length=200), nullable=False),
        sa.Column("shutter", sa.String(length=200), nullable=False),
        sa.Column("finish", sa.String(length=250), nullable=False),
        sa.Column("visible_price", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("lookup_price", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("admin_resolution", sa.String(length=20), nullable=True),
        sa.Column("resolved_price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["master_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id"),
    )
    op.create_table(
        "quotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("project_reference", sa.String(length=200), nullable=False),
        sa.Column("quote_date", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quotations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quotations_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quotations_customer_name"), ["customer_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quotations_number"), ["number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_quotations_project_reference"),
            ["project_reference"],
            unique=False,
        )

    op.create_table(
        "quotation_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["quotation_id"], ["quotations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quotation_sections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quotation_sections_quotation_id"),
            ["quotation_id"],
            unique=False,
        )

    op.create_table(
        "quotation_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("wording", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quotation_id"], ["quotations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quotation_terms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quotation_terms_quotation_id"),
            ["quotation_id"],
            unique=False,
        )

    op.create_table(
        "quotation_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("pdf", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quotation_id", "revision"),
    )
    with op.batch_alter_table("quotation_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quotation_versions_quotation_id"),
            ["quotation_id"],
            unique=False,
        )

    op.create_table(
        "quotation_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("line_key", sa.String(length=80), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"], ["quotation_sections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quotation_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quotation_items_section_id"), ["section_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quotation_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotation_items_section_id"))

    op.drop_table("quotation_items")
    with op.batch_alter_table("quotation_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotation_versions_quotation_id"))

    op.drop_table("quotation_versions")
    with op.batch_alter_table("quotation_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotation_terms_quotation_id"))

    op.drop_table("quotation_terms")
    with op.batch_alter_table("quotation_sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotation_sections_quotation_id"))

    op.drop_table("quotation_sections")
    with op.batch_alter_table("quotations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotations_project_reference"))
        batch_op.drop_index(batch_op.f("ix_quotations_number"))
        batch_op.drop_index(batch_op.f("ix_quotations_customer_name"))
        batch_op.drop_index(batch_op.f("ix_quotations_created_by"))

    op.drop_table("quotations")
    op.drop_table("price_conflicts")
    op.drop_table("login_sessions")
    op.drop_table("customers")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("settings")
    op.drop_table("quotation_counters")
    with op.batch_alter_table("master_products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_master_products_item"))

    op.drop_table("master_products")
    op.drop_table("login_attempts")
    # ### end Alembic commands ###
