"""area catalogue project rates and Excel snapshots

Revision ID: e20e112c2343
Revises: 29c9874f4150
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'e20e112c2343'
down_revision: Union[str, Sequence[str], None] = '29c9874f4150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # PostgreSQL assigns a real name to the initial unnamed UNIQUE constraint.
    # The batch naming convention only supplies names for unnamed SQLite ones;
    # it does not rename existing PostgreSQL constraints.
    constraints = sa.inspect(op.get_bind()).get_unique_constraints('price_conflicts')
    with op.batch_alter_table('price_conflicts', naming_convention={'uq':'uq_%(table_name)s_%(column_0_name)s'}) as batch_op:
        for constraint in constraints:
            if constraint['column_names'] == ['product_id']:
                name = constraint['name'] or 'uq_price_conflicts_product_id'
                batch_op.drop_constraint(op.f(name), type_='unique')
        batch_op.create_index('ix_price_conflicts_product_id',['product_id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('area_products',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('area_id', 'product_id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source_file', sa.LargeBinary(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_price_history_product_id'), ['product_id'], unique=False)

    op.create_table('setting_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_versions_key'), ['key'], unique=False)

    op.create_table('source_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(length=200), nullable=False),
    sa.Column('source_sheet', sa.String(length=200), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_prices_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    with op.batch_alter_table('master_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('unit', sa.String(length=40), nullable=False, server_default='Sq Ft'))
        batch_op.add_column(sa.Column('measurement_mode', sa.String(length=20), nullable=False, server_default='area'))
        batch_op.add_column(sa.Column('source_sheet', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('catalogue', sa.String(length=40), nullable=False, server_default='legacy'))
        batch_op.create_index(batch_op.f('ix_master_products_catalogue'), ['catalogue'], unique=False)

    with op.batch_alter_table('quotation_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excel', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('generated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_version_generated_by', 'users', ['generated_by'], ['id'])

    # ### end Alembic commands ###
def downgrade() -> None:
    raise RuntimeError('This migration stores immutable Excel versions and source history. Restore a pre-upgrade backup instead of deleting business records.')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_versions', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_version_generated_by', type_='foreignkey')
        batch_op.drop_column('generated_by')
        batch_op.drop_column('excel')

    with op.batch_alter_table('master_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_products_catalogue'))
        batch_op.drop_column('catalogue')
        batch_op.drop_column('source_sheet')
        batch_op.drop_column('measurement_mode')
        batch_op.drop_column('unit')
        batch_op.drop_column('category')
        batch_op.drop_column('specification')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')

    with op.batch_alter_table('source_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_prices_product_id'))

    op.drop_table('source_prices')
    with op.batch_alter_table('setting_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_versions_key'))

    op.drop_table('setting_versions')
    with op.batch_alter_table('master_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_price_history_product_id'))

    op.drop_table('master_price_history')
    op.drop_table('import_batches')
    op.drop_table('area_products')
    op.drop_table('areas')
    # ### end Alembic commands ###
